sudo: false

matrix:
  include:
    - rvm: 1.8.7
      gemfile: Gemfile.1.8.7
    - rvm: 1.9.2
      gemfile: Gemfile-oldruby
    - rvm: 1.9.3
      gemfile: Gemfile-oldruby
    - rvm: 2.0.0
      gemfile: Gemfile-oldruby
    - rvm: 2.1.0
      gemfile: Gemfile
    - rvm: 2.2.0
      gemfile: Gemfile
    - rvm: 2.3.0
      gemfile: Gemfile
    - rvm: 2.4.0
      gemfile: Gemfile
    - rvm: jruby-18mode
      gemfile: Gemfile.1.8.7
    - rvm: jruby-19mode
      gemfile: Gemfile-oldruby
    - rvm: rbx
      gemfile: Gemfile
  fast_finish: true
  allow_failures:
    # rbx is broken on Travis right now
    - rvm: rbx

branches:
  only:
    - master

before_install:
  - gem install bundler

script: "bundle exec rake test_with_coveralls"
